version: "3.8"

services:
  database:
    container_name: web-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: free_me_babe_after_malloc
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: free_me_babe_after_malloc
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - framework_web_network

  php:
    container_name: web-php_apache
    build: ./docker/php/
    volumes:
      - ./code:/var/www/html/
      - vendor:/var/www/vendor
      - var:/var/www/var
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/virtual_host.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    env_file:
      - ./code/.env
    networks:
      - framework_web_network

  node:
    container_name: web-node
    build: ./docker/node
    volumes:
      - ./code:/app
    ports:
      - "8082:8082"
    networks:
      - framework_web_network

volumes:
  vendor:
  var:
  mysqldata:

networks:
  framework_web_network:
    driver: bridge
