version: "3.8"

services:
  database:
    container_name: web-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: free_me_babe_after_malloc
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: free_me_babe_after_malloc
    ports:
      - 3306:3306
    networks:
      - framework_web_network

  phpmyadmin:
    container_name: web-phpmyadmin
    image: phpmyadmin:5.1.1-apache
    ports: 
      - 8080:80
    volumes:
      - ./mysql_config.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=web-database
    networks:
      - framework_web_network

  php:
    container_name: web-php_apache
    image: php:8.0-apache
    volumes:
      - ./code:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./virtual_host.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8000:80
    env_file:
      - ./code/.env
    networks:
      - framework_web_network

networks:
  framework_web_network:
    driver: bridge
